In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df_train = pd.read_csv('train.csv')
#df_test = pd.read_csv('test.csv')

In [2]:
df_train.shape#, df_test.shape

(1787571, 34)

In [3]:
def preprocessing_1(df):
    import datetime
    # перевод дат из строк в даты 
    df['DTIME_CREDIT'] = pd.to_datetime( df['DTIME_CREDIT'], format="%d.%m.%Y" )
    df['DTIME_CREDIT_ENDDATE'] = pd.to_datetime( df['DTIME_CREDIT_ENDDATE'], format="%d.%m.%Y" )
    df['DTIME_CREDIT_ENDDATE_FACT'] = pd.to_datetime( df['DTIME_CREDIT_ENDDATE_FACT'], format="%d.%m.%Y" )
    df['DTIME_CREDIT_UPDATE'] = pd.to_datetime( df['DTIME_CREDIT_UPDATE'], format="%d.%m.%Y" )
    
    # удаляем выбросы дат
#     df = df[df['DTIME_CREDIT_UPDATE'] < 
#                                         datetime.datetime.strptime('01.01.2017','%d.%m.%Y') ]
#     df = df[df['DTIME_CREDIT_UPDATE'] > 
#                                         datetime.datetime.strptime('01.01.2000','%d.%m.%Y') ]
    
    # будем группировать по полям ['ID','SK_DATE_DECISION','DTIME_CREDIT','DTIME_CREDIT_ENDDATE',
    # 'AMT_CREDIT_SUM','CREDIT_CURRENCY']. Поэтому почистим от NaN эти поля
    df_fill_ed = df.copy()
    df_fill_ed.DTIME_CREDIT_ENDDATE[df_fill_ed.DTIME_CREDIT_ENDDATE.isnull()] = \
        df_fill_ed.DTIME_CREDIT_ENDDATE_FACT[df_fill_ed.DTIME_CREDIT_ENDDATE.isnull()]
    df_fill_ed.DTIME_CREDIT_ENDDATE.fillna(0, inplace=True)
    df_null = pd.isnull(df_fill_ed[['ID',
             'SK_DATE_DECISION',
             'DTIME_CREDIT',
             'DTIME_CREDIT_ENDDATE',
             'AMT_CREDIT_SUM',
             'CREDIT_CURRENCY']]).unstack()
    drop_indexes = [ a[1] for a in np.array(df_null[df_null].index) ]
    df_fill_ed = df_fill_ed.drop(df_fill_ed.index[drop_indexes])
    return df_fill_ed

In [7]:
def preprocess_fields(df):
    retDF = df.copy()
    vals = list(range(6)) + ['C','X']
    PMTstr = pd.DataFrame([{'TEXT_PAYMENT_DISCIPLINE_%s' % (str(j)): str(i).count(str(j)) for j in vals} 
                           for i in retDF.TEXT_PAYMENT_DISCIPLINE])
    retDF = retDF.join(PMTstr).drop(['TEXT_PAYMENT_DISCIPLINE'], axis=1)
    del PMTstr
    
    # преобразуем CREDIT_TYPE
    vals = [0,1,2,3,4,5,6,7,8,9,10,18,19,99]
    PMTstr = pd.DataFrame([{'CREDIT_TYPE_%s' % (str(j)): str(i).count(str(j)) for j in vals} 
                           for i in retDF.CREDIT_TYPE])
    retDF = retDF.join(PMTstr).drop(['CREDIT_TYPE'], axis=1)
    del PMTstr
    
    # преобразуем CREDIT_ACTIVE
    vals = [0,1,2,3]
    PMTstr = pd.DataFrame([{'CREDIT_ACTIVE_%s' % (str(j)): str(i).count(str(j)) for j in vals} 
                           for i in retDF.CREDIT_ACTIVE])
    retDF = retDF.join(PMTstr).drop(['CREDIT_ACTIVE'], axis=1)
    return retDF

In [5]:
df_train = preprocessing_1(df_train)
#df_test  = preprocessing_1(df_test)

c:\users\администратор\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [8]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
df_train = preprocess_fields(df_train)
#df_test = preprocess_text_discipline(df_test)

MemoryError:

In [ ]:
df_train.head(5)
#df_test.head(5)

In [7]:
columns = list(df_train.columns)
i = 0
for column in columns:
    if(np.all(pd.notnull(df_train[column]))):
        print(column)
        i += 1
print(i)

# columns = list(df_test.columns)
# i = 0
# for column in columns:
#     if(np.all(pd.notnull(df_test[column]))):
#         print(column)
#         i += 1
# print(i)

ID
SK_DATE_DECISION
DEF
NUM_SOURCE
CREDIT_ACTIVE
CREDIT_COLLATERAL
CREDIT_CURRENCY
DTIME_CREDIT
CREDIT_DAY_OVERDUE
DTIME_CREDIT_ENDDATE
CNT_CREDIT_PROLONG
AMT_CREDIT_SUM
AMT_CREDIT_SUM_OVERDUE
CREDIT_SUM_TYPE
CREDIT_TYPE
DTIME_CREDIT_UPDATE
CREDIT_DELAY30
CREDIT_DELAY5
CREDIT_DELAY60
CREDIT_DELAY90
CREDIT_DELAY_MORE
AMT_REQ_SOURCE_HOUR
AMT_REQ_SOURCE_DAY
AMT_REQ_SOURCE_WEEK
AMT_REQ_SOURCE_MON
AMT_REQ_SOURCE_QRT
AMT_REQ_SOURCE_YEAR
27

In [8]:
col_grp = ['ID',
           'SK_DATE_DECISION',
           'CREDIT_CURRENCY',
           'DTIME_CREDIT',
           'DTIME_CREDIT_ENDDATE']
col_drop = ['NUM_SOURCE',
            'DTIME_CREDIT_ENDDATE_FACT',
            'DTIME_CREDIT_UPDATE']
dfPreSrc = df_train.drop(col_drop,axis=1).groupby(col_grp)

In [16]:
del dfPreSrc

In [15]:
dfPreSrc.reset_index(level=0).groupby(['ID'])

        DEF  CREDIT_ACTIVE
ID
24368   0.0       0.555556
24369   0.0       0.452381
24370   0.0       0.200000
24372   0.0       0.166667
24373   0.0       0.428571
24374   0.0       0.000000
24375   0.0       0.000000
24376   0.0       1.000000
24377   0.0       0.400000
24378   0.0       0.222222
24379   0.0       0.500000
24380   0.0       0.500000
24381   0.0       0.000000
24382   0.0       0.200000
24383   0.0       1.000000
24384   0.0       0.333333
24385   0.0       0.333333
24386   0.0       0.238095
24387   0.0       0.000000
24388   0.0       0.500000
24389   0.0       0.357143
24390   0.0       0.000000
24391   0.0       0.333333
24392   0.0       0.214286
24393   0.0       0.000000
24394   0.0       0.000000
24395   0.0       0.312500
24396   0.0       0.000000
24397   0.0       0.000000
24398   0.0       0.333333
...     ...            ...
174604  0.0       1.000000
174605  0.0       0.111111
174606  1.0       0.666667
174607  0.0       0.000000
174608  0.0       0.352941
174610  0.0       0.375000
174612  0.0       0.000000
174613  0.0       0.250000
174614  0.0       1.000000
174615  0.0       0.125000
174616  0.0       0.394737
174617  0.0       0.333333
174618  0.0       0.500000
174620  0.0       0.444444
174622  0.0       0.500000
174623  0.0       0.500000
174624  0.0       0.500000
174625  0.0       1.000000
174626  0.0       0.500000
174627  0.0       0.000000
174628  0.0       0.666667
174629  0.0       0.095238
174630  0.0       0.285714
174631  0.0       0.055556
174632  0.0       1.000000
174633  0.0       1.000000
174635  0.0       0.000000
174636  0.0       0.133333
174638  0.0       0.222222
175099  0.0       0.666667

[135155 rows x 2 columns]